version: '3'

vars:
  FE_PORT: 3000

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:
    desc: Builds the frontent image
    cmds:
      - docker build -t devx-frontend:latest .

  run:
    desc: Runs the frontent container
    cmds:
      - docker run -d --rm --name devx-frontend -p "{{.FE_PORT}}":"{{.FE_PORT}}" devx-frontend

  stop:
    desc: Stops the frontend container
    cmds:
      - docker stop devx-frontend