---
services:
  db:
    container_name: devx_app_db
    image: postgres
    ports:
      - 5432:5432
    # restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres # what the api is currently configured for
      POSTGRES_DB: app_database
    volumes:
      - './database:/docker-entrypoint-initdb.d/:ro'
  api:
    container_name: devx_api
    image: devx-api
    ports:
      - 3001:3001
    environment:
      - API_DB_ENDPOINT=db
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - 3000:3000
    environment:
      API_URL: api