---
services:
  db:
    container_name: devx-app-db
    image: postgres
    ports:
      - 5432:5432
    # restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres # what the api is currently configured for
      POSTGRES_DB: app_database
    volumes:
      - './database:/docker-entrypoint-initdb.d/:ro'
  api:
    container_name: devx-api
    image: devx-api
    ports:
      - 3001:3001
    environment:
      - API_DB_ENDPOINT=db
      - DEBUG_METRICS='true'
  frontend:
    container_name: devx-frontend
    image: devx-frontend
    ports:
      - 3000:3000
  grafana:
    container_name: devx-grafana
    image: grafana/grafana-oss
    ports:
      - 3002:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'