# https://taskfile.dev

version: '3'

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build-all:
    desc: Builds docker images for all components 
    cmds:
      - task: api:build
      