# https://taskfile.dev

version: '3'

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend
  load_test:
    taskfile: ./load_test/Taskfile.yml
    dir: ./load_test

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build-all:
    desc: Builds docker images for all components 
    cmds:
      - task: api:build
      - task: frontend:build
      - task: load_test:build
