{
 "title": "MVS dashboard loki",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{status=~\"4..\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{status=~\"3..\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{status=~\"2..\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{status=~\"2..\"}[1h])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=~\"2..\"}[1h]) / rate(flask_http_request_duration_seconds_count{status=~\"2..\"}[1h])\r\n"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Transactions added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"devx-api\", event=\"Transaction created\"}[5m])"
    }
   ]
  },
  { "title": "Login attempts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total login attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"devx-api\", event=~\"User logged in\"}[5m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"devx-api\", event=~\"Bad username or password\"}[5m])"
    }
   ]
  },
  {
   "title": "Successful logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"devx-api\", event=\"User logged in\"}[1h])"
    }
   ]
  },
  {
   "title": "Unsuccessful login attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=\"devx-api\", event=\"Bad username or password\"}[5m])"
    }
   ]
  }
 ]
}