# https://taskfile.dev

version: '3'

vars:
  API_PORT: 3001

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:
    desc: Builds the dex-api docker image and applies the latest tag
    cmds:
      - docker build -t devx-api:latest .

  run:
    desc: Runs the devx-api container
    cmds:
      - docker run -d --rm --name devx-api -p "{{.API_PORT}}":"{{.API_PORT}}" devx-api
  
  stop:
    desc: Stops the devx-api container
    cmds:
      - docker stop devx-api